version: '3'

services:
  db:
    build: ./db
    hostname: mysql
    ports:
      - "3306:3306"
  web:
    build: ./web
    ports: 
      - "8080:8080"
    hostname: nodejs
    environment:
      WAIT_HOSTS: mysql:3306