version: '3'
services:
  app:
    container_name: docker-test
    restart: always
    build: .
    ports: 
      - '3000:3000'
    links:
      - mysql
  db:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: password